import csv
import sys
import os
import time
import PySimpleGUI as sg

def ConstructGUI():
    sg.theme("Default1")

    layout = [
        [sg.Text('XER Splitter', justification='center', font=("",15))],
        [sg.Text('XER File', size=(20,1)),      
            sg.InputText("", size=(35,1), key='-INPUTFILE-'), sg.FileBrowse(file_types=(('P6 XER File', '*.xer'),))],
        [sg.Text('Output Folder', size=(20,1)),
            sg.InputText("", size=(35,1), key='-OUTPUTFOLDER-'), sg.FolderBrowse()],
        [sg.Frame(title='Options',layout=[      
            [sg.Checkbox('Ignore Problematic Tables',key='-IGNORETABLES-', default=True, tooltip="Ignores RISKTYPE & POMS Tables:\nThey are auto-generated by P6 and cause problems")],
            [sg.Frame(title='Output File Type',layout=[     
                [sg.Radio('.csv', 'csv', key='-TYPECSV-', default=True), sg.Radio('.xlsx', "xlsx",key='-TYPEXLSX-', disabled=True, tooltip="Not Currently Supported")]])
                ]])
            ],
        [sg.Text('_' * 60)],
        [sg.Text('Select Tables')],
        [sg.Button('Split'), sg.Exit()]
        ]

    window = sg.Window("XER Splitter", layout)

    while True:
        event, values = window.read()
        print(event,values)
        if event == sg.WIN_CLOSED or event == 'Exit':
            break 

    window.close()

if __name__ == "__main__":
    ConstructGUI()