import PySimpleGUI as sg
import _thread
import webbrowser



class GUI:

    def __init__(self, args):
        self.args = args
        self.window = sg.Window("XER Splitter", self.GetLayout(), finalize=True)

        introText = "Welcome to the XER Splitter\n\n"
        self.window["-OUTPUT-"].update(introText)

    def GetLayout(self):
        sg.theme("Default1")

        OptionsLayout = [      
                [sg.Checkbox('Ignore Problematic Tables',key='-IGNORETABLES-', default=(not self.args.allTables), tooltip="Ignores RISKTYPE & POBS Tables:\nThey are auto-generated by P6 and have been known to cause problems")],
                [sg.Frame(title='Output File Type',layout=[     
                    [sg.Radio('.csv', 'type', key='-TYPECSV-', default=(self.args.type=='csv')), sg.Radio('.xlsx', "type",key='-TYPEXLSX-', default=(self.args.type=="xlsx"))]])
                ]
        ]

        mainLayout = [
            [sg.Text('.XER File', size=(20,1))],      
            [sg.InputText(size=(35,1), key='-INPUTFILE-', default_text=(self.args.inputFile)), sg.FileBrowse(file_types=(('P6 XER File', '*.xer'),))],
            [sg.Text('Output Folder', size=(20,1))],
            [sg.InputText(size=(35,1), key='-OUTPUTFOLDER-', default_text=(self.args.outputDir)), sg.FolderBrowse()],
            [sg.Frame(title='Options',layout=OptionsLayout)],
            [sg.Text('_' * 50)],
            [sg.Text('Press \'Split\' to begin', key="-WORKINGTEXT-"), sg.Text("", size=(35,1), justification="right", visible=False, key="-STATSTEXT-")],
            [sg.Output(size=(50,15), key='-OUTPUT-')],
            [sg.Button(button_text='Split', key="-SPLIT-"), 
                sg.Button(button_text="Clear"), 
                sg.CloseButton("Close", key="-STOPBUTTON-"), 
                sg.Text("github.com/JaiLaff", size=(27,1),justification = "right", enable_events=True, key="-GITHUB-", tooltip="Click to go to the Github Repo!")
            ]
        ]

        return mainLayout

    def Update(self, valueString=None, success=None):
        if success == False:
            self.window['-WORKINGTEXT-'].update(value="Error Found")
            self.window['-SPLIT-'].update(disabled=False)

        self.window["-STATSTEXT-"].update(visible=True)
        if valueString is not None: self.window["-STATSTEXT-"].update(value=valueString)

        if success == True:
            self.window['-WORKINGTEXT-'].update(value="Complete!")
            self.window['-SPLIT-'].update(disabled=False)
        
    def ProcessEvent(self):
        event, values = self.window.read()

        if event in (sg.WIN_CLOSED, 'Exit', "Close"):
            return -1

        if event == "Clear":
            self.window['-OUTPUT-'].update("")

        if event == "-SPLIT-":
            self.window['-WORKINGTEXT-'].update(value="Working...")
            self.window['-SPLIT-'].update(disabled=True)
            if values["-TYPECSV-"]: self.args.type='csv'
            if values["-TYPEXLSX-"]: self.args.type='xlsx'
            self.args.inputFile = values["-INPUTFILE-"]
            self.args.outputDir = values["-OUTPUTFOLDER-"]
            self.args.allTables = not values["-IGNORETABLES-"]
            return 1

        if event == "-GITHUB-":
            webbrowser.open("https://github.com/JaiLaff")

        return 0